const texto = "Ol&aacute;, tudo bem com voc&circ;e?";
const regex = /&([a-zA-Z]+);/g;
const acentos = {
  Aacute: "Á",
  aacute: "á",
  Acirc: "Â",
  acirc: "â",
  Agrave: "À",
  agrave: "à",
  Aring: "Å",
  aring: "å",
  Atilde: "Ã",
  atilde: "ã",
  Eacute: "É",
  eacute: "é",
  Ecirc: "Ê",
  ecirc: "ê",
  Egrave: "È",
  egrave: "è",
  Iacute: "Í",
  iacute: "í",
  Icirc: "Î",
  icirc: "î",
  Igrave: "Ì",
  igrave: "ì",
  Oacute: "Ó",
  oacute: "ó",
  Ocirc: "Ô",
  ocirc: "ô",
  Ograve: "Ò",
  ograve: "ò",
  Otilde: "Õ",
  otilde: "õ",
  Uacute: "Ú",
  uacute: "ú",
  Ucirc: "Û",
  ucirc: "û",
  Ugrave: "Ù",
  ugrave: "ù",
  Ccedil: "Ç",
  ccedil: "ç",
  Ntilde: "Ñ",
  ntilde: "ñ",
};

const textoConvertido = texto.replace(regex, (match, entity) => {
  return acentos[entity] || match;
});
